apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        # This version uses Tomcat 10 to support Jakarta EE
        image: vprofile-app-image 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: JDBC_URL
          value: "jdbc:mysql://vprodb:3306/vprofiledb"
        
