name: "vProfile App Deployment"

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'kubernetes/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: gitops-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build and push the docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Inject the new image name into the deployment manifest
          # Make sure 'vprofile-app-image' is the image name in your appdeploy.yaml
          sed -i "s|vprofile-app-image|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" kubernetes/appdeploy.yaml

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name vpro-eks-mesh

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/secret.yaml
          kubectl apply -f kubernetes/dbdeploy.yaml
          kubectl apply -f kubernetes/dbservice.yaml
          kubectl apply -f kubernetes/mcdep.yaml
          kubectl apply -f kubernetes/mcservice.yaml
          kubectl apply -f kubernetes/rmqdeploy.yaml
          kubectl apply -f kubernetes/rmqservice.yaml
          kubectl apply -f kubernetes/appdeploy.yaml
          kubectl apply -f kubernetes/appservice.yaml
